// Sample data for development/testing
export const sampleProducts = [
  {
    id: 1,
    name: "Maple Syrup",
    description: "Pure Canadian maple syrup 250ml",
    price: "12.99",
    image: "/images/maple-syrup.jpg",
    canadianPercentage: 87,
    category: "Pantry Staples",
  },
  {
    id: 2,
    name: "Organic Apples",
    description: "Fresh Ontario apples, 1kg bag",
    price: "5.49",
    image: "/images/apples.jpg",
    canadianPercentage: 42,
    category: "Fresh Produce",
  },
  {
    id: 3,
    name: "Cheddar Cheese",
    description: "Aged Canadian cheddar 200g",
    price: "7.99",
    image: "/images/cheddar.jpg",
    canadianPercentage: 96,
    category: "Dairy & Alternatives",
  },
  {
    id: 4,
    name: "Whole Grain Bread",
    description: "Artisan whole grain loaf",
    price: "4.99",
    image: "/images/bread.jpg",
    canadianPercentage: 63,
    category: "Bakery",
  },
  {
    id: 5,
    name: "Atlantic Salmon",
    description: "Fresh Atlantic salmon fillet 300g",
    price: "15.99",
    image: "/images/salmon.jpg",
    canadianPercentage: 100,
    category: "Meat & Protein",
  },
  {
    id: 6,
    name: "Mixed Nuts",
    description: "Roasted mixed nuts with cranberries 500g",
    price: "10.49",
    image: "/images/mixed-nuts.jpg",
    canadianPercentage: 29,
    category: "Snacks",
  },
  {
    id: 7,
    name: "Organic Granola",
    description: "Cranberry almond granola 400g",
    price: "8.99",
    image: "/images/cranberry-granola.jpg",
    canadianPercentage: 78,
    category: "Breakfast",
  },
  {
    id: 8,
    name: "Almond Milk",
    description: "Vanilla almond milk 1L",
    price: "4.49",
    image: "/images/vanilla-almond-milk.jpg",
    canadianPercentage: 54,
    category: "Dairy & Alternatives",
  },
  {
    id: 9,
    name: "Peanut Butter",
    description: "Natural peanut butter 500g",
    price: "6.99",
    image: "/images/peanut-butter.jpg",
    canadianPercentage: 91,
    category: "Pantry Staples",
  },
  {
    id: 10,
    name: "Blueberries",
    description: "Fresh wild blueberries, 1 pint",
    price: "4.99",
    image: "/images/blueberries.jpg",
    canadianPercentage: 33,
    category: "Fresh Produce",
  },
  {
    id: 11,
    name: "Greek Yogurt",
    description: "Plain Greek yogurt 750g",
    price: "5.99",
    image: "/images/greek-yogurt.jpg",
    canadianPercentage: 65,
    category: "Dairy & Alternatives",
  },
  {
    id: 12,
    name: "Honey",
    description: "Raw wildflower honey 500g",
    price: "9.49",
    image: "/images/honey.jpg",
    canadianPercentage: 99,
    category: "Pantry Staples",
  },
  {
    id: 13,
    name: "Trail Mix",
    description: "Energy trail mix with chocolate chips 300g",
    price: "7.49",
    image: "/images/trail-mix.jpg",
    canadianPercentage: 12,
    category: "Snacks",
  },
  {
    id: 14,
    name: "Oatmeal",
    description: "Steel-cut oats 1kg",
    price: "4.99",
    image: "/images/oatmeal.jpg",
    canadianPercentage: 88,
    category: "Breakfast",
  },
  {
    id: 15,
    name: "Chicken Breast",
    description: "Free-range chicken breast 500g",
    price: "12.99",
    image: "/images/chicken-breast.jpg",
    canadianPercentage: 47,
    category: "Meat & Protein",
  },
  {
    id: 16,
    name: "Dark Chocolate",
    description: "70% dark chocolate bar 100g",
    price: "3.99",
    image: "/images/dark-chocolate.jpg",
    canadianPercentage: 23,
    category: "Snacks",
  },
  {
    id: 17,
    name: "Quinoa",
    description: "Organic white quinoa 1kg",
    price: "8.99",
    image: "/images/quinoa.jpg",
    canadianPercentage: 74,
    category: "Pantry Staples",
  },
  {
    id: 18,
    name: "Carrots",
    description: "Fresh organic carrots, 1kg",
    price: "3.49",
    image: "/images/carrots.jpg",
    canadianPercentage: 51,
    category: "Fresh Produce",
  },
  {
    id: 19,
    name: "Butter",
    description: "Unsalted Canadian butter 454g",
    price: "6.49",
    image: "/images/butter.jpg",
    canadianPercentage: 84,
    category: "Dairy & Alternatives",
  },
  {
    id: 20,
    name: "Pasta",
    description: "Whole wheat spaghetti 500g",
    price: "2.99",
    image: "/images/pasta.jpg",
    canadianPercentage: 9,
    category: "Pantry Staples",
  },
  // Additional 40 products
  {
    id: 21,
    name: "Strawberries",
    description: "Fresh strawberries, 1 pint",
    price: "4.99",
    image: "/images/strawberries.jpg",
    canadianPercentage: 67,
    category: "Fresh Produce",
  },
  {
    id: 22,
    name: "Almond Butter",
    description: "Natural almond butter 500g",
    price: "8.99",
    image: "/images/almond-butter.jpg",
    canadianPercentage: 45,
    category: "Pantry Staples",
  },
  {
    id: 23,
    name: "Coconut Water",
    description: "Pure coconut water 1L",
    price: "3.99",
    image: "/images/coconut-water.jpg",
    canadianPercentage: 12,
    category: "Beverages",
  },
  {
    id: 24,
    name: "Spinach",
    description: "Fresh organic spinach, 1 bunch",
    price: "2.99",
    image: "/images/spinach.jpg",
    canadianPercentage: 89,
    category: "Fresh Produce",
  },
  {
    id: 25,
    name: "Eggs",
    description: "Free-range eggs, dozen",
    price: "4.49",
    image: "/images/eggs.jpg",
    canadianPercentage: 95,
    category: "Dairy & Alternatives",
  },
  {
    id: 26,
    name: "Rice",
    description: "Basmati rice 1kg",
    price: "6.99",
    image: "/images/rice.jpg",
    canadianPercentage: 34,
    category: "Pantry Staples",
  },
  {
    id: 27,
    name: "Tomatoes",
    description: "Fresh Roma tomatoes, 1kg",
    price: "3.49",
    image: "/images/tomatoes.jpg",
    canadianPercentage: 76,
    category: "Fresh Produce",
  },
  {
    id: 28,
    name: "Avocado",
    description: "Fresh avocado, each",
    price: "1.99",
    image: "/images/avocado.jpg",
    canadianPercentage: 22,
    category: "Fresh Produce",
  },
  {
    id: 29,
    name: "Orange Juice",
    description: "Freshly squeezed orange juice 1L",
    price: "5.99",
    image: "/images/orange-juice.jpg",
    canadianPercentage: 58,
    category: "Beverages",
  },
  {
    id: 30,
    name: "Potatoes",
    description: "Russet potatoes, 5kg bag",
    price: "7.49",
    image: "/images/potatoes.jpg",
    canadianPercentage: 81,
    category: "Fresh Produce",
  },
  {
    id: 31,
    name: "Cereal",
    description: "Whole grain cereal 500g",
    price: "4.99",
    image: "/images/cereal.jpg",
    canadianPercentage: 39,
    category: "Breakfast",
  },
  {
    id: 32,
    name: "Ice Cream",
    description: "Vanilla ice cream 1L",
    price: "6.49",
    image: "/images/ice-cream.jpg",
    canadianPercentage: 72,
    category: "Frozen",
  },
  {
    id: 33,
    name: "Lettuce",
    description: "Fresh iceberg lettuce, each",
    price: "1.99",
    image: "/images/lettuce.jpg",
    canadianPercentage: 48,
    category: "Fresh Produce",
  },
  {
    id: 34,
    name: "Coffee",
    description: "Ground coffee 500g",
    price: "9.99",
    image: "/images/coffee.jpg",
    canadianPercentage: 29,
    category: "Beverages",
  },
  {
    id: 35,
    name: "Tea",
    description: "Green tea bags, 20 count",
    price: "3.99",
    image: "/images/tea.jpg",
    canadianPercentage: 64,
    category: "Beverages",
  },
  {
    id: 36,
    name: "Cucumber",
    description: "Fresh cucumber, each",
    price: "1.49",
    image: "/images/cucumber.jpg",
    canadianPercentage: 85,
    category: "Fresh Produce",
  },
  {
    id: 37,
    name: "Bell Peppers",
    description: "Mixed bell peppers, 1kg",
    price: "4.99",
    image: "/images/bell-peppers.jpg",
    canadianPercentage: 92,
    category: "Fresh Produce",
  },
  {
    id: 38,
    name: "Beef Steak",
    description: "Grass-fed beef steak 300g",
    price: "14.99",
    image: "/images/beef-steak.jpg",
    canadianPercentage: 77,
    category: "Meat & Protein",
  },
  {
    id: 39,
    name: "Shrimp",
    description: "Frozen shrimp 500g",
    price: "12.99",
    image: "/images/shrimp.jpg",
    canadianPercentage: 66,
    category: "Frozen",
  },
  {
    id: 40,
    name: "Mango",
    description: "Fresh mango, each",
    price: "2.49",
    image: "/images/mango.jpg",
    canadianPercentage: 18,
    category: "Fresh Produce",
  },
  {
    id: 41,
    name: "Pineapple",
    description: "Fresh pineapple, each",
    price: "3.99",
    image: "/images/pineapple.jpg",
    canadianPercentage: 21,
    category: "Fresh Produce",
  },
  {
    id: 42,
    name: "Yogurt Drink",
    description: "Strawberry yogurt drink 500ml",
    price: "2.99",
    image: "/images/yogurt-drink.jpg",
    canadianPercentage: 53,
    category: "Dairy & Alternatives",
  },
  {
    id: 43,
    name: "Bagels",
    description: "Whole wheat bagels, 6 count",
    price: "3.49",
    image: "/images/bagels.jpg",
    canadianPercentage: 88,
    category: "Bakery",
  },
  {
    id: 44,
    name: "Cheese Pizza",
    description: "Frozen cheese pizza 400g",
    price: "7.99",
    image: "/images/cheese-pizza.jpg",
    canadianPercentage: 36,
    category: "Frozen",
  },
  {
    id: 45,
    name: "Sausages",
    description: "Pork sausages, 500g",
    price: "9.49",
    image: "/images/sausages.jpg",
    canadianPercentage: 74,
    category: "Meat & Protein",
  },
  {
    id: 46,
    name: "Milk",
    description: "2% milk 1L",
    price: "2.99",
    image: "/images/milk.jpg",
    canadianPercentage: 97,
    category: "Dairy & Alternatives",
  },
  {
    id: 47,
    name: "Chips",
    description: "Potato chips, 200g",
    price: "3.49",
    image: "/images/chips.jpg",
    canadianPercentage: 41,
    category: "Snacks",
  },
  {
    id: 48,
    name: "Popcorn",
    description: "Microwave popcorn, 3 bags",
    price: "4.49",
    image: "/images/popcorn.jpg",
    canadianPercentage: 59,
    category: "Snacks",
  },
  {
    id: 49,
    name: "Watermelon",
    description: "Fresh watermelon, each",
    price: "6.99",
    image: "/images/watermelon.jpg",
    canadianPercentage: 82,
    category: "Fresh Produce",
  },
  {
    id: 50,
    name: "Cabbage",
    description: "Green cabbage, each",
    price: "2.49",
    image: "/images/cabbage.jpg",
    canadianPercentage: 68,
    category: "Fresh Produce",
  },
  {
    id: 51,
    name: "Pork Chops",
    description: "Bone-in pork chops, 500g",
    price: "10.99",
    image: "/images/pork-chops.jpg",
    canadianPercentage: 79,
    category: "Meat & Protein",
  },
  {
    id: 52,
    name: "Frozen Peas",
    description: "Frozen green peas, 500g",
    price: "3.99",
    image: "/images/frozen-peas.jpg",
    canadianPercentage: 62,
    category: "Frozen",
  },
  {
    id: 53,
    name: "Canned Tuna",
    description: "Canned tuna in water, 170g",
    price: "2.49",
    image: "/images/canned-tuna.jpg",
    canadianPercentage: 44,
    category: "Pantry Staples",
  },
  {
    id: 54,
    name: "Chocolate Cake",
    description: "Chocolate cake slice, 200g",
    price: "4.99",
    image: "/images/chocolate-cake.jpg",
    canadianPercentage: 71,
    category: "Bakery",
  },
  {
    id: 55,
    name: "Frozen Pizza",
    description: "Pepperoni frozen pizza, 400g",
    price: "8.99",
    image: "/images/frozen-pizza.jpg",
    canadianPercentage: 37,
    category: "Frozen",
  },
  {
    id: 56,
    name: "Apple Juice",
    description: "100% apple juice, 1L",
    price: "3.49",
    image: "/images/apple-juice.jpg",
    canadianPercentage: 50,
    category: "Beverages",
  },
  {
    id: 57,
    name: "Zucchini",
    description: "Fresh zucchini, 1kg",
    price: "3.99",
    image: "/images/zucchini.jpg",
    canadianPercentage: 86,
    category: "Fresh Produce",
  },
  {
    id: 58,
    name: "Frozen Berries",
    description: "Mixed frozen berries, 500g",
    price: "6.99",
    image: "/images/frozen-berries.jpg",
    canadianPercentage: 60,
    category: "Frozen",
  },
  {
    id: 59,
    name: "Canned Beans",
    description: "Canned black beans, 400g",
    price: "1.99",
    image: "/images/canned-beans.jpg",
    canadianPercentage: 33,
    category: "Pantry Staples",
  },
  {
    id: 60,
    name: "Frozen Fries",
    description: "Frozen French fries, 1kg",
    price: "4.99",
    image: "/images/frozen-fries.jpg",
    canadianPercentage: 49,
    category: "Frozen",
  },
];
