// Sample data for development/testing
export const products = [
  {
    id: 1,
    name: "Maple Syrup",
    description: "Pure Canadian maple syrup 250ml",
    price: "12.99",
    image: "/images/maple-syrup.jpg",
    canadianPercentage: 100,
    category: "Pantry Staples",
  },
  {
    id: 2,
    name: "Organic Apples",
    description: "Fresh Ontario apples, 1kg bag",
    price: "5.49",
    image: "/images/apples.jpg",
    canadianPercentage: 100,
    category: "Fresh Produce",
  },
  {
    id: 3,
    name: "Cheddar Cheese",
    description: "Aged Canadian cheddar 200g",
    price: "7.99",
    image: "/images/cheddar.jpg",
    canadianPercentage: 100,
    category: "Dairy & Alternatives",
  },
  {
    id: 4,
    name: "Whole Grain Bread",
    description: "Artisan whole grain loaf",
    price: "4.99",
    image: "/images/bread.jpg",
    canadianPercentage: 85,
    category: "Bakery",
  },
  {
    id: 5,
    name: "Atlantic Salmon",
    description: "Fresh Atlantic salmon fillet 300g",
    price: "15.99",
    image: "/images/salmon.jpg",
    canadianPercentage: 100,
    category: "Meat & Protein",
  },
  {
    id: 6,
    name: "Mixed Nuts",
    description: "Roasted mixed nuts with cranberries 500g",
    price: "10.49",
    image: "/images/mixed-nuts.jpg",
    canadianPercentage: 60,
    category: "Snacks",
  },
  {
    id: 7,
    name: "Organic Granola",
    description: "Cranberry almond granola 400g",
    price: "8.99",
    image: "/images/cranberry-granola.jpg",
    canadianPercentage: 90,
    category: "Breakfast",
  },
  {
    id: 8,
    name: "Almond Milk",
    description: "Vanilla almond milk 1L",
    price: "4.49",
    image: "/images/vanilla-almond-milk.jpg",
    canadianPercentage: 75,
    category: "Dairy & Alternatives",
  },
  {
    id: 9,
    name: "Peanut Butter",
    description: "Natural peanut butter 500g",
    price: "6.99",
    image: "/images/peanut-butter.jpg",
    canadianPercentage: 80,
    category: "Pantry Staples",
  },
  {
    id: 10,
    name: "Blueberries",
    description: "Fresh wild blueberries, 1 pint",
    price: "4.99",
    image: "/images/blueberries.jpg",
    canadianPercentage: 100,
    category: "Fresh Produce",
  },
  {
    id: 11,
    name: "Greek Yogurt",
    description: "Plain Greek yogurt 750g",
    price: "5.99",
    image: "/images/greek-yogurt.jpg",
    canadianPercentage: 95,
    category: "Dairy & Alternatives",
  },
  {
    id: 12,
    name: "Honey",
    description: "Raw wildflower honey 500g",
    price: "9.49",
    image: "/images/honey.jpg",
    canadianPercentage: 100,
    category: "Pantry Staples",
  },
  {
    id: 13,
    name: "Trail Mix",
    description: "Energy trail mix with chocolate chips 300g",
    price: "7.49",
    image: "/images/trail-mix.jpg",
    canadianPercentage: 70,
    category: "Snacks",
  },
  {
    id: 14,
    name: "Oatmeal",
    description: "Steel-cut oats 1kg",
    price: "4.99",
    image: "/images/oatmeal.jpg",
    canadianPercentage: 85,
    category: "Breakfast",
  },
  {
    id: 15,
    name: "Chicken Breast",
    description: "Free-range chicken breast 500g",
    price: "12.99",
    image: "/images/chicken-breast.jpg",
    canadianPercentage: 100,
    category: "Meat & Protein",
  },
  {
    id: 16,
    name: "Dark Chocolate",
    description: "70% dark chocolate bar 100g",
    price: "3.99",
    image: "/images/dark-chocolate.jpg",
    canadianPercentage: 50,
    category: "Snacks",
  },
  {
    id: 17,
    name: "Quinoa",
    description: "Organic white quinoa 1kg",
    price: "8.99",
    image: "/images/quinoa.jpg",
    canadianPercentage: 90,
    category: "Pantry Staples",
  },
  {
    id: 18,
    name: "Carrots",
    description: "Fresh organic carrots, 1kg",
    price: "3.49",
    image: "/images/carrots.jpg",
    canadianPercentage: 100,
    category: "Fresh Produce",
  },
  {
    id: 19,
    name: "Butter",
    description: "Unsalted Canadian butter 454g",
    price: "6.49",
    image: "/images/butter.jpg",
    canadianPercentage: 100,
    category: "Dairy & Alternatives",
  },
  {
    id: 20,
    name: "Pasta",
    description: "Whole wheat spaghetti 500g",
    price: "2.99",
    image: "/images/pasta.jpg",
    canadianPercentage: 70,
    category: "Pantry Staples",
  },
];
